# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011c17bc33655dece151c682950a7ba9f00589da7e6c2374ce94e12f074fa6ce56cabb88b6d9abb4766ed8358d997f52693fb69e324a11d46b7dca33adc67a3b

test:
  secret_key_base: c6dd4ca2689fb6275c28a0e1a97ad26ffd0c5fbdebacaac72c85a2db8112c65fda027409037f40abeed87c4219daaa67859bcaefb7836df8717d8d62a178c325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
